import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
	style: ["normal"],
	subsets: ["latin"],
	variable: "--font-inter",
	preload: true,
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
	modal,
}: {
	children: React.ReactNode;
	modal: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={`${inter.variable} font-sans`}>
				{children}
				{modal}
			</body>
		</html>
	);
}
